apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
    {{- include "validator.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "validator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "validator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "validator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: RPC_HOST
              value: {{.Values.environment.RPC_HOST | quote}}
            - name: FREQUENCY
              value: {{.Values.environment.FREQUENCY | quote}}
            - name: MAX_SLIPPAGE
              value: {{.Values.environment.MAX_SLIPPAGE | quote}}
            - name: PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "validator.fullname" .}}
                  key: PRIVATE_KEY
            - name: LOG_LEVEL
              value: {{.Values.environment.LOG_LEVEL | quote}}
            - name: NETWORK_ID
              value: {{.Values.environment.NETWORK_ID | quote}}
            - name: INFURA_PROJECT_ID
              value: {{.Values.environment.INFURA_PROJECT_ID | quote}}
            - name: PRICE_FEED_API
              value: {{.Values.environment.PRICE_FEED_API | quote}}
            - name: LOGS_PATH
              value: {{.Values.environment.LOGS_PATH | quote}}
            - name: HOST
              value: {{.Values.environment.HOST | quote}}
            - name: PORT
              value: {{.Values.environment.PORT | quote}}
            - name: NODE_ENV
              value: {{.Values.environment.NODE_ENV | quote}}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
