apiVersion: v1
kind: Secret
metadata:
  name: {{ include "validator.fullname" . }}
  labels:
    app: {{ include "validator.name" . }}
    chart: {{ include "validator.chart" . }}
type: Opaque
data:
  PRIVATE_KEY: {{.Values.environment.PRIVATE_KEY | b64enc | quote}}
