# Use %VAR% to reference template-time variables
default:
  image: '${REGISTRY}/install:%TREE_HASH%'
  interruptible: true
  before_script:
    - cd /src
    - ./scripts/ci/init_repo_in_container.bash

variables:
  GIT_STRATEGY: none

🎨 lint:all:
  script:
    - yarn lint:all
  rules:
    - if: $CI_MERGE_REQUEST_ID

🧪:
  parallel:
    matrix:
      - TARGET: [contracts, yield-farming, jrt-investors, crypto-utils]
  script:
    - yarn test $TARGET
  rules:
    - if: $CI_MERGE_REQUEST_ID
