yarnPath: .yarn/releases/yarn-3.1.1.cjs
nodeLinker: node-modules
npmRegistryServer: https://gitlab.com/api/v4/packages/npm/

# Disable information messages that are not important
logFilters:
  - code: YN0013
    level: discard
  - code: YN0076
    level: discard
  - code: YN0007
    level: discard
