const defaultAssets = [
  {
    name: 'Jarvis Synthetic Euro',
    symbol: 'jEUR',
    priceFeed: 'EURUSD',
    uiFeed: 'EURUSD',
    contract: null,
    derivative: null,
    price: '0',
    collateral: '0',
    totalTokens: '0',
  },
  {
    name: 'Jarvis Synthetic Swiss Franc',
    symbol: 'jCHF',
    priceFeed: 'USDCHF',
    uiFeed: 'CHFUSD',
    contract: null,
    derivative: null,
    price: '0',
    collateral: '0',
    totalTokens: '0',
  },
  {
    name: 'Jarvis Synthetic British Pound',
    symbol: 'jGBP',
    priceFeed: 'GBPUSD',
    uiFeed: 'GBPUSD',
    contract: null,
    derivative: null,
    price: '0',
    collateral: '0',
    totalTokens: '0',
  },
  {
    name: 'Jarvis Synthetic Gold',
    symbol: 'jXAU',
    priceFeed: 'XAUUSD',
    uiFeed: 'XAUUSD',
    contract: null,
    derivative: null,
    price: '0',
    collateral: '0',
    totalTokens: '0',
  },
  {
    name: 'Jarvis Synthetic S&P500',
    symbol: 'jSPX',
    priceFeed: 'SPXUSD',
    uiFeed: 'SPXUSD',
    contract: null,
    derivative: null,
    price: '0',
    collateral: '0',
    totalTokens: '0',
  },
  {
    name: 'Jarvis Synthetic Crude Oil',
    symbol: 'jXTI',
    priceFeed: 'XTIUSD',
    uiFeed: 'XTIUSD',
    contract: null,
    derivative: null,
    price: '0',
    collateral: '0',
    totalTokens: '0',
  },
  {
    name: 'Jarvis Synthetic Silver',
    symbol: 'jXAG',
    priceFeed: 'XAGUSD',
    uiFeed: 'XAGUSD',
    contract: null,
    derivative: null,
    price: '0',
    collateral: '0',
    totalTokens: '0',
  },
];

export default defaultAssets;
