apiVersion: v1
kind: Service
metadata:
  name: {{ include "validator-meta-tx.fullname" . }}
  labels:
    {{- include "validator-meta-tx.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "validator-meta-tx.selectorLabels" . | nindent 4 }}
