/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ContractAllowedOnChanPriceFeed extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): ContractAllowedOnChanPriceFeed;
  clone(): ContractAllowedOnChanPriceFeed;
  methods: {
    collateral(): NonPayableTransactionObject<string>;

    mintInPool(
      mintParams: [
        string,
        number | string | BN,
        number | string | BN,
        number | string | BN,
        number | string | BN,
      ],
      approveAmount: number | string | BN,
    ): NonPayableTransactionObject<void>;

    pool(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
