/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ContractAllowed extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ContractAllowed;
  clone(): ContractAllowed;
  methods: {
    collateral(): NonPayableTransactionObject<string>;

    pool(): NonPayableTransactionObject<string>;

    mintInPool(
      mintParams: [
        string,
        string,
        number | string,
        number | string,
        number | string,
        number | string,
        number | string
      ],
      signature: [number | string, string | number[], string | number[]],
      approveAmount: number | string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
