/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type InterfaceImplementationChanged = ContractEventLog<{
  interfaceName: string;
  newImplementationAddress: string;
  0: string;
  1: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;

export interface Finder extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): Finder;
  clone(): Finder;
  methods: {
    interfacesImplemented(
      arg0: string | number[]
    ): NonPayableTransactionObject<string>;

    /**
     * Returns the address of the current owner.
     */
    owner(): NonPayableTransactionObject<string>;

    /**
     * Leaves the contract without owner. It will not be possible to call `onlyOwner` functions anymore. Can only be called by the current owner. NOTE: Renouncing ownership will leave the contract without an owner, thereby removing any functionality that is only available to the owner.
     */
    renounceOwnership(): NonPayableTransactionObject<void>;

    /**
     * Transfers ownership of the contract to a new account (`newOwner`). Can only be called by the current owner.
     */
    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    /**
     * Updates the address of the contract that implements `interfaceName`.
     * @param implementationAddress address of the implementation contract.
     * @param interfaceName bytes32 of the interface name that is either changed or registered.
     */
    changeImplementationAddress(
      interfaceName: string | number[],
      implementationAddress: string
    ): NonPayableTransactionObject<void>;

    /**
     * Gets the address of the contract that implements the given `interfaceName`.
     * @param interfaceName queried interface.
     */
    getImplementationAddress(
      interfaceName: string | number[]
    ): NonPayableTransactionObject<string>;
  };
  events: {
    InterfaceImplementationChanged(
      cb?: Callback<InterfaceImplementationChanged>
    ): EventEmitter;
    InterfaceImplementationChanged(
      options?: EventOptions,
      cb?: Callback<InterfaceImplementationChanged>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(
    event: "InterfaceImplementationChanged",
    cb: Callback<InterfaceImplementationChanged>
  ): void;
  once(
    event: "InterfaceImplementationChanged",
    options: EventOptions,
    cb: Callback<InterfaceImplementationChanged>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;
}
