/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type AddedSharedMember = ContractEventLog<{
  roleId: string;
  newMember: string;
  manager: string;
  0: string;
  1: string;
  2: string;
}>;
export type NewProposal = ContractEventLog<{
  id: string;
  transactions: [string, string, string][];
  0: string;
  1: [string, string, string][];
}>;
export type ProposalExecuted = ContractEventLog<{
  id: string;
  transactionIndex: string;
  0: string;
  1: string;
}>;
export type RemovedSharedMember = ContractEventLog<{
  roleId: string;
  oldMember: string;
  manager: string;
  0: string;
  1: string;
  2: string;
}>;
export type ResetExclusiveMember = ContractEventLog<{
  roleId: string;
  newMember: string;
  manager: string;
  0: string;
  1: string;
  2: string;
}>;

export interface Governor extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): Governor;
  clone(): Governor;
  methods: {
    addMember(
      roleId: number | string | BN,
      newMember: string,
    ): NonPayableTransactionObject<void>;

    executeProposal(
      id: number | string | BN,
      transactionIndex: number | string | BN,
    ): PayableTransactionObject<void>;

    getCurrentTime(): NonPayableTransactionObject<string>;

    getMember(
      roleId: number | string | BN,
    ): NonPayableTransactionObject<string>;

    getProposal(
      id: number | string | BN,
    ): NonPayableTransactionObject<[[string, string, string][], string]>;

    holdsRole(
      roleId: number | string | BN,
      memberToCheck: string,
    ): NonPayableTransactionObject<boolean>;

    numProposals(): NonPayableTransactionObject<string>;

    proposals(arg0: number | string | BN): NonPayableTransactionObject<string>;

    propose(
      transactions: [string, number | string | BN, string | number[]][],
    ): NonPayableTransactionObject<void>;

    removeMember(
      roleId: number | string | BN,
      memberToRemove: string,
    ): NonPayableTransactionObject<void>;

    renounceMembership(
      roleId: number | string | BN,
    ): NonPayableTransactionObject<void>;

    resetMember(
      roleId: number | string | BN,
      newMember: string,
    ): NonPayableTransactionObject<void>;

    setCurrentTime(
      time: number | string | BN,
    ): NonPayableTransactionObject<void>;

    timerAddress(): NonPayableTransactionObject<string>;
  };
  events: {
    AddedSharedMember(cb?: Callback<AddedSharedMember>): EventEmitter;
    AddedSharedMember(
      options?: EventOptions,
      cb?: Callback<AddedSharedMember>,
    ): EventEmitter;

    NewProposal(cb?: Callback<NewProposal>): EventEmitter;
    NewProposal(
      options?: EventOptions,
      cb?: Callback<NewProposal>,
    ): EventEmitter;

    ProposalExecuted(cb?: Callback<ProposalExecuted>): EventEmitter;
    ProposalExecuted(
      options?: EventOptions,
      cb?: Callback<ProposalExecuted>,
    ): EventEmitter;

    RemovedSharedMember(cb?: Callback<RemovedSharedMember>): EventEmitter;
    RemovedSharedMember(
      options?: EventOptions,
      cb?: Callback<RemovedSharedMember>,
    ): EventEmitter;

    ResetExclusiveMember(cb?: Callback<ResetExclusiveMember>): EventEmitter;
    ResetExclusiveMember(
      options?: EventOptions,
      cb?: Callback<ResetExclusiveMember>,
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: 'AddedSharedMember', cb: Callback<AddedSharedMember>): void;
  once(
    event: 'AddedSharedMember',
    options: EventOptions,
    cb: Callback<AddedSharedMember>,
  ): void;

  once(event: 'NewProposal', cb: Callback<NewProposal>): void;
  once(
    event: 'NewProposal',
    options: EventOptions,
    cb: Callback<NewProposal>,
  ): void;

  once(event: 'ProposalExecuted', cb: Callback<ProposalExecuted>): void;
  once(
    event: 'ProposalExecuted',
    options: EventOptions,
    cb: Callback<ProposalExecuted>,
  ): void;

  once(event: 'RemovedSharedMember', cb: Callback<RemovedSharedMember>): void;
  once(
    event: 'RemovedSharedMember',
    options: EventOptions,
    cb: Callback<RemovedSharedMember>,
  ): void;

  once(event: 'ResetExclusiveMember', cb: Callback<ResetExclusiveMember>): void;
  once(
    event: 'ResetExclusiveMember',
    options: EventOptions,
    cb: Callback<ResetExclusiveMember>,
  ): void;
}
