/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface IDerivativeDeployment extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): IDerivativeDeployment;
  clone(): IDerivativeDeployment;
  methods: {
    addAdminAndPool(adminAndPool: string): NonPayableTransactionObject<void>;

    collateralCurrency(): NonPayableTransactionObject<string>;

    getAdminMembers(): NonPayableTransactionObject<string[]>;

    getPoolMembers(): NonPayableTransactionObject<string[]>;

    renounceAdmin(): NonPayableTransactionObject<void>;

    tokenCurrency(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
