/* File autogenerated by synthereum-lib. Do not edit manually. */

import type { Tagged } from '@jarvis-network/web3-utils/base/tagged-type';

export type KnownContract =
  | Tagged<AccessControl, 'AccessControl'>
  | Tagged<ERC20, 'ERC20'>
  | Tagged<FinderInterface, 'FinderInterface'>
  | Tagged<HitchensUnorderedKeySet, 'HitchensUnorderedKeySet'>
  | Tagged<IDerivative, 'IDerivative'>
  | Tagged<IDerivativeDeployment, 'IDerivativeDeployment'>
  | Tagged<IERC20, 'IERC20'>
  | Tagged<IStandardERC20, 'IStandardERC20'>
  | Tagged<Migrations, 'Migrations'>
  | Tagged<SynthereumTIC, 'SynthereumTIC'>
  | Tagged<SynthereumTICInterface, 'SynthereumTICInterface'>
  | Tagged<TICCreator, 'TICCreator'>;

import type { AccessControl } from './AccessControl';
export type { AccessControl };
import type {
  RoleAdminChanged as AccessControl_RoleAdminChanged,
  RoleGranted as AccessControl_RoleGranted,
  RoleRevoked as AccessControl_RoleRevoked,
} from './AccessControl';
export namespace AccessControl_Events {
  export type RoleAdminChanged = AccessControl_RoleAdminChanged;
  export type RoleGranted = AccessControl_RoleGranted;
  export type RoleRevoked = AccessControl_RoleRevoked;
}

import type { ERC20 } from './ERC20';
export type { ERC20 };
import type {
  Approval as ERC20_Approval,
  Transfer as ERC20_Transfer,
} from './ERC20';
export namespace ERC20_Events {
  export type Approval = ERC20_Approval;
  export type Transfer = ERC20_Transfer;
}

import type { FinderInterface } from './FinderInterface';
export type { FinderInterface };

import type { HitchensUnorderedKeySet } from './HitchensUnorderedKeySet';
export type { HitchensUnorderedKeySet };
import type { LogUpdate as HitchensUnorderedKeySet_LogUpdate } from './HitchensUnorderedKeySet';
export namespace HitchensUnorderedKeySet_Events {
  export type LogUpdate = HitchensUnorderedKeySet_LogUpdate;
}

import type { IDerivative } from './IDerivative';
export type { IDerivative };

import type { IDerivativeDeployment } from './IDerivativeDeployment';
export type { IDerivativeDeployment };

import type { IERC20 } from './IERC20';
export type { IERC20 };
import type {
  Approval as IERC20_Approval,
  Transfer as IERC20_Transfer,
} from './IERC20';
export namespace IERC20_Events {
  export type Approval = IERC20_Approval;
  export type Transfer = IERC20_Transfer;
}

import type { IStandardERC20 } from './IStandardERC20';
export type { IStandardERC20 };
import type {
  Approval as IStandardERC20_Approval,
  Transfer as IStandardERC20_Transfer,
} from './IStandardERC20';
export namespace IStandardERC20_Events {
  export type Approval = IStandardERC20_Approval;
  export type Transfer = IStandardERC20_Transfer;
}

import type { Migrations } from './Migrations';
export type { Migrations };

import type { SynthereumTIC } from './SynthereumTIC';
export type { SynthereumTIC };
import type {
  ExchangeApproved as SynthereumTIC_ExchangeApproved,
  ExchangeRejected as SynthereumTIC_ExchangeRejected,
  ExchangeRequested as SynthereumTIC_ExchangeRequested,
  MintApproved as SynthereumTIC_MintApproved,
  MintRejected as SynthereumTIC_MintRejected,
  MintRequested as SynthereumTIC_MintRequested,
  RedeemApproved as SynthereumTIC_RedeemApproved,
  RedeemRejected as SynthereumTIC_RedeemRejected,
  RedeemRequested as SynthereumTIC_RedeemRequested,
  RoleAdminChanged as SynthereumTIC_RoleAdminChanged,
  RoleGranted as SynthereumTIC_RoleGranted,
  RoleRevoked as SynthereumTIC_RoleRevoked,
  SetFeePercentage as SynthereumTIC_SetFeePercentage,
  SetFeeRecipients as SynthereumTIC_SetFeeRecipients,
} from './SynthereumTIC';
export namespace SynthereumTIC_Events {
  export type ExchangeApproved = SynthereumTIC_ExchangeApproved;
  export type ExchangeRejected = SynthereumTIC_ExchangeRejected;
  export type ExchangeRequested = SynthereumTIC_ExchangeRequested;
  export type MintApproved = SynthereumTIC_MintApproved;
  export type MintRejected = SynthereumTIC_MintRejected;
  export type MintRequested = SynthereumTIC_MintRequested;
  export type RedeemApproved = SynthereumTIC_RedeemApproved;
  export type RedeemRejected = SynthereumTIC_RedeemRejected;
  export type RedeemRequested = SynthereumTIC_RedeemRequested;
  export type RoleAdminChanged = SynthereumTIC_RoleAdminChanged;
  export type RoleGranted = SynthereumTIC_RoleGranted;
  export type RoleRevoked = SynthereumTIC_RoleRevoked;
  export type SetFeePercentage = SynthereumTIC_SetFeePercentage;
  export type SetFeeRecipients = SynthereumTIC_SetFeeRecipients;
}

import type { SynthereumTICInterface } from './SynthereumTICInterface';
export type { SynthereumTICInterface };

import type { TICCreator } from './TICCreator';
export type { TICCreator };

export type {
  Callback,
  ContractEventLog,
  ContractEventEmitter,
  NonPayableTx,
  PayableTx,
  NonPayableTransactionObject,
  PayableTransactionObject,
  BlockType,
  BaseContract,
} from './types';
