/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ISynthereumPoolInteraction extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): ISynthereumPoolInteraction;
  clone(): ISynthereumPoolInteraction;
  methods: {
    exchangeMint(
      srcDerivative: string,
      derivative: string,
      collateralAmount: number | string | BN,
      numTokens: number | string | BN,
    ): NonPayableTransactionObject<void>;

    getPriceFeedIdentifier(): NonPayableTransactionObject<string>;

    isDerivativeAdmitted(
      derivative: string,
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
