/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ISynthereumPoolDeployment extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ISynthereumPoolDeployment;
  clone(): ISynthereumPoolDeployment;
  methods: {
    /**
     * Get Synthereum finder of the pool
     */
    synthereumFinder(): NonPayableTransactionObject<string>;

    /**
     * Get Synthereum version
     */
    version(): NonPayableTransactionObject<string>;

    /**
     * Get the collateral token
     */
    collateralToken(): NonPayableTransactionObject<string>;

    /**
     * Get the synthetic token associated to this pool
     */
    syntheticToken(): NonPayableTransactionObject<string>;

    /**
     * Get the synthetic token symbol associated to this pool
     */
    syntheticTokenSymbol(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
