/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ISynthereumManager extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): ISynthereumManager;
  clone(): ISynthereumManager;
  methods: {
    emergencyShutdown(derivatives: string[]): NonPayableTransactionObject<void>;

    grantSynthereumRole(
      contracts: string[],
      roles: (string | number[])[],
      accounts: string[],
    ): NonPayableTransactionObject<void>;

    renounceSynthereumRole(
      contracts: string[],
      roles: (string | number[])[],
    ): NonPayableTransactionObject<void>;

    revokeSynthereumRole(
      contracts: string[],
      roles: (string | number[])[],
      accounts: string[],
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
