/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ISynthereumFactoryVersioning extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): ISynthereumFactoryVersioning;
  clone(): ISynthereumFactoryVersioning;
  methods: {
    getDerivativeFactoryVersion(
      version: number | string | BN,
    ): NonPayableTransactionObject<string>;

    getPoolFactoryVersion(
      version: number | string | BN,
    ): NonPayableTransactionObject<string>;

    numberOfVerisonsOfDerivativeFactory(): NonPayableTransactionObject<string>;

    numberOfVerisonsOfPoolFactory(): NonPayableTransactionObject<string>;

    removeDerivativeFactory(
      version: number | string | BN,
    ): NonPayableTransactionObject<void>;

    removePoolFactory(
      version: number | string | BN,
    ): NonPayableTransactionObject<void>;

    setDerivativeFactory(
      version: number | string | BN,
      derivativeFactory: string,
    ): NonPayableTransactionObject<void>;

    setPoolFactory(
      version: number | string | BN,
      poolFactory: string,
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
