/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface ISynthereumPoolRegistry extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): ISynthereumPoolRegistry;
  clone(): ISynthereumPoolRegistry;
  methods: {
    registerPool(
      syntheticTokenSymbol: string,
      collateralToken: string,
      poolVersion: number | string,
      pool: string
    ): NonPayableTransactionObject<void>;

    isPoolDeployed(
      poolSymbol: string,
      collateral: string,
      poolVersion: number | string,
      pool: string
    ): NonPayableTransactionObject<boolean>;

    getPools(
      poolSymbol: string,
      collateral: string,
      poolVersion: number | string
    ): NonPayableTransactionObject<string[]>;

    getCollaterals(): NonPayableTransactionObject<string[]>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
