/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface OptimisticRequester extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): OptimisticRequester;
  clone(): OptimisticRequester;
  methods: {
    priceDisputed(
      identifier: string | number[],
      timestamp: number | string | BN,
      ancillaryData: string | number[],
      refund: number | string | BN,
    ): NonPayableTransactionObject<void>;

    priceProposed(
      identifier: string | number[],
      timestamp: number | string | BN,
      ancillaryData: string | number[],
    ): NonPayableTransactionObject<void>;

    priceSettled(
      identifier: string | number[],
      timestamp: number | string | BN,
      ancillaryData: string | number[],
      price: number | string | BN,
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
