/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface OracleAncillaryInterface extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): OracleAncillaryInterface;
  clone(): OracleAncillaryInterface;
  methods: {
    getPrice(
      identifier: string | number[],
      time: number | string | BN,
      ancillaryData: string | number[],
    ): NonPayableTransactionObject<string>;

    hasPrice(
      identifier: string | number[],
      time: number | string | BN,
      ancillaryData: string | number[],
    ): NonPayableTransactionObject<boolean>;

    requestPrice(
      identifier: string | number[],
      time: number | string | BN,
      ancillaryData: string | number[],
    ): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
