/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface RegistryInterface extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): RegistryInterface;
  clone(): RegistryInterface;
  methods: {
    addPartyToContract(party: string): NonPayableTransactionObject<void>;

    getAllRegisteredContracts(): NonPayableTransactionObject<string[]>;

    getRegisteredContracts(
      party: string,
    ): NonPayableTransactionObject<string[]>;

    isContractRegistered(
      contractAddress: string,
    ): NonPayableTransactionObject<boolean>;

    isPartyMemberOfContract(
      party: string,
      contractAddress: string,
    ): NonPayableTransactionObject<boolean>;

    registerContract(
      parties: string[],
      contractAddress: string,
    ): NonPayableTransactionObject<void>;

    removePartyFromContract(party: string): NonPayableTransactionObject<void>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
