/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface RegistryInterface extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): RegistryInterface;
  clone(): RegistryInterface;
  methods: {
    registerContract(
      parties: string[],
      contractAddress: string
    ): NonPayableTransactionObject<void>;

    isContractRegistered(
      contractAddress: string
    ): NonPayableTransactionObject<boolean>;

    getRegisteredContracts(
      party: string
    ): NonPayableTransactionObject<string[]>;

    getAllRegisteredContracts(): NonPayableTransactionObject<string[]>;

    addPartyToContract(party: string): NonPayableTransactionObject<void>;

    removePartyFromContract(party: string): NonPayableTransactionObject<void>;

    isPartyMemberOfContract(
      party: string,
      contractAddress: string
    ): NonPayableTransactionObject<boolean>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
