/* File autogenerated by synthereum-lib. Do not edit manually. */
/* eslint-disable */

import BN from 'bn.js';
import { ContractOptions } from 'web3-eth-contract';
import { EventLog } from 'web3-core';
import { EventEmitter } from 'events';
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from './types';

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface SynthereumTICFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions,
  ): SynthereumTICFactory;
  clone(): SynthereumTICFactory;
  methods: {
    createTIC(
      derivative: string,
      finder: string,
      version: number | string | BN,
      roles: [string, string, string, string],
      startingCollateralization: number | string | BN,
      fee: [[number | string | BN], string[], (number | string | BN)[]],
    ): NonPayableTransactionObject<string>;

    deploymentSignature(): NonPayableTransactionObject<string>;

    synthereumFinder(): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
