/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export interface SynthereumTICFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): SynthereumTICFactory;
  clone(): SynthereumTICFactory;
  methods: {
    deploymentSignature(): NonPayableTransactionObject<string>;

    synthereumFinder(): NonPayableTransactionObject<string>;

    createTIC(
      derivative: string,
      finder: string,
      version: number | string,
      roles: [string, string, string, string],
      startingCollateralization: number | string,
      fee: [[number | string], string[], (number | string)[]]
    ): NonPayableTransactionObject<string>;
  };
  events: {
    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };
}
