/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type CreatedPerpetual = ContractEventLog<{
  perpetualAddress: string;
  deployerAddress: string;
  0: string;
  1: string;
}>;

export interface SynthereumDerivativeFactory extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): SynthereumDerivativeFactory;
  clone(): SynthereumDerivativeFactory;
  methods: {
    /**
     * Returns the bytes4 signature of the function used for the deployment of a contract in a factory
     */
    deploymentSignature(): NonPayableTransactionObject<string>;

    /**
     * Gets the current time. Will return the last time set in `setCurrentTime` if running in test mode. Otherwise, it will return the block timestamp.
     */
    getCurrentTime(): NonPayableTransactionObject<string>;

    /**
     * Will revert if not running in test mode.
     * Sets the current time.
     * @param time timestamp to set current Testable time to.
     */
    setCurrentTime(time: number | string): NonPayableTransactionObject<void>;

    synthereumFinder(): NonPayableTransactionObject<string>;

    timerAddress(): NonPayableTransactionObject<string>;

    tokenFactoryAddress(): NonPayableTransactionObject<string>;

    createPerpetual(
      params: [
        string,
        string | number[],
        string,
        string,
        string,
        [number | string],
        [number | string],
        [number | string],
        [number | string],
        [number | string],
        number | string,
        number | string,
        string,
        string[],
        string[]
      ]
    ): NonPayableTransactionObject<string>;
  };
  events: {
    CreatedPerpetual(cb?: Callback<CreatedPerpetual>): EventEmitter;
    CreatedPerpetual(
      options?: EventOptions,
      cb?: Callback<CreatedPerpetual>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "CreatedPerpetual", cb: Callback<CreatedPerpetual>): void;
  once(
    event: "CreatedPerpetual",
    options: EventOptions,
    cb: Callback<CreatedPerpetual>
  ): void;
}
