// SPDX-License-Identifier: AGPL-3.0-only
pragma solidity >=0.8.0;

interface ILendingStorageManager {
  struct PoolStorage {
    bytes32 lendingModuleId; // hash of the lending module id associated with the LendingInfo the pool currently is using
    address collateral; // collateral address of the pool
    address interestBearingToken; // interest token address of the pool
    uint256 JRTBuybackShare; // share of dao interest used to buyback JRT
    uint256 daoInterestShare; // share of total interest generated by the pool directed to the DAO
    uint256 collateralDeposited; // amount of collateral currently deposited in the MoneyMarket
    uint256 unclaimedDaoJRT; // amount of interest to be claimed to buyback JRT
    uint256 unclaimedDaoCommission; // amount of interest to be claimed as commission (in collateral)
  }

  struct LendingInfo {
    address lendingModule; // address of the ILendingModule interface implementer
    bytes args; // encoded args the ILendingModule implementer might need
  }

  /**
   * @notice sets a ILendingModule implementer info
   * @param id string identifying a specific ILendingModule implementer
   * @param lendingInfo see lendingInfo struct
   */
  function setLendingModule(string memory id, LendingInfo memory lendingInfo)
    external;

  /**
   * @notice sets an address as the swap module associated to a specific collateral
   * @dev the swapModule must implement the IJRTSwapModule interface
   * @param collateral collateral address associated to the swap module
   * @param swapModule IJRTSwapModule implementer contract
   */
  function setSwapModule(address collateral, address swapModule) external;

  /**
   * @notice set shares on interest generated by a pool collateral on the lending storage manager
   * @param pool pool address to set shares on
   * @param daoInterestShare share of total interest generated assigned to the dao
   * @param jrtBuybackShare share of the total dao interest used to buyback jrt from an AMM
   */
  function setShares(
    address pool,
    uint256 daoInterestShare,
    uint256 jrtBuybackShare
  ) external;

  /**
   * @notice store data for lending manager associated to a pool
   * @param lendingID string identifying the associated ILendingModule implementer
   * @param pool pool address to set info
   * @param collateral collateral address of the pool
   * @param interestBearingToken address of the interest token in use
   * @param daoInterestShare share of total interest generated assigned to the dao
   * @param jrtBuybackShare share of the total dao interest used to buyback jrt from an AMM
   */
  function setPoolStorage(
    string memory lendingID,
    address pool,
    address collateral,
    address interestBearingToken,
    uint256 daoInterestShare,
    uint256 jrtBuybackShare
  ) external;

  /**
   * @notice assign oldPool storage information and state to newPool address and deletes oldPool storage slot
   * @dev is used when a pool is redeployed and the liquidity transferred over
   * @param oldPool address of old pool to migrate storage from
   * @param newPool address of the new pool receiving state of oldPool
   */
  function migratePool(address oldPool, address newPool) external;

  /**
   * @notice sets new lending info on a pool
   * @dev used when migrating liquidity from one lending module (and money market), to a new one
   * @dev The new lending module info must be have been previously set in the storage manager
   * @param newLendingID id associated to the new lending module info
   * @param pool address of the pool whose associated lending module is being migrated
   * @param newInterestToken address of the interest token of the new Lending Module (can be set blank)
   * @return poolData with the updated state
   * @return lendingInfo of the new lending module
   */
  function migrateLendingModule(
    string memory newLendingID,
    address pool,
    address newInterestToken
  ) external returns (PoolStorage memory, LendingInfo memory);

  /**
   * @notice updates storage of a pool
   * @dev should be callable only by LendingManager after state-changing operations
   * @param pool address of the pool to update values
   * @param collateralDeposited updated amount of collateral deposited
   * @param daoJRT updated amount of unclaimed interest for JRT buyback
   * @param daoInterest updated amount of unclaimed interest as dao commission
   */
  function updateValues(
    address pool,
    uint256 collateralDeposited,
    uint256 daoJRT,
    uint256 daoInterest
  ) external;

  /**
   * @notice reads PoolStorage and LendingInfo of a pool
   * @param pool address of the pool to read storage
   * @return poolData pool struct info
   * @return lendingInfo information of the lending module associated with the pool
   */
  function getPoolStorage(address pool)
    external
    view
    returns (PoolStorage memory poolData, LendingInfo memory lendingInfo);

  /**
   * @notice reads PoolStorage of a pool
   * @param pool address of the pool to read storage
   * @return poolData pool struct info
   */
  function getPoolData(address pool)
    external
    view
    returns (PoolStorage memory poolData);

  /**
   * @notice reads the JRT Buyback module associated to a collateral
   * @param collateral address of the collateral to retrieve module
   * @return address interface implementer of the IJRTSwapModule
   */
  function getCollateralSwapModule(address collateral)
    external
    view
    returns (address);

  /**
   * @notice reads the interest beaaring token address associated to a pool
   * @param pool address of the pool to retrieve interest token
   * @return interestTokenAddr address of the interest token
   */
  function getInterestBearingToken(address pool)
    external
    view
    returns (address interestTokenAddr);
}
