/* File autogenerated by synthereum-lib. Do not edit manually. */

import type { AbiItem } from 'web3-utils';
import type { Tagged } from '@jarvis-network/web3-utils/base/tagged-type';

import type { AccessControl } from '../typechain/AccessControl';
export const AccessControl_Abi = require('./AccessControl.json') as Tagged<
  AbiItem[],
  AccessControl
>;

import type { AddressWhitelist } from '../typechain/AddressWhitelist';
export const AddressWhitelist_Abi = require('./AddressWhitelist.json') as Tagged<
  AbiItem[],
  AddressWhitelist
>;

import type { AdministrateeInterface } from '../typechain/AdministrateeInterface';
export const AdministrateeInterface_Abi = require('./AdministrateeInterface.json') as Tagged<
  AbiItem[],
  AdministrateeInterface
>;

import type { AggregatorV3Interface } from '../typechain/AggregatorV3Interface';
export const AggregatorV3Interface_Abi = require('./AggregatorV3Interface.json') as Tagged<
  AbiItem[],
  AggregatorV3Interface
>;

import type { ContractAllowed } from '../typechain/ContractAllowed';
export const ContractAllowed_Abi = require('./ContractAllowed.json') as Tagged<
  AbiItem[],
  ContractAllowed
>;

import type { ContractCreator } from '../typechain/ContractCreator';
export const ContractCreator_Abi = require('./ContractCreator.json') as Tagged<
  AbiItem[],
  ContractCreator
>;

import type { DesignatedVoting } from '../typechain/DesignatedVoting';
export const DesignatedVoting_Abi = require('./DesignatedVoting.json') as Tagged<
  AbiItem[],
  DesignatedVoting
>;

import type { DesignatedVotingFactory } from '../typechain/DesignatedVotingFactory';
export const DesignatedVotingFactory_Abi = require('./DesignatedVotingFactory.json') as Tagged<
  AbiItem[],
  DesignatedVotingFactory
>;

import type { ERC20 } from '../typechain/ERC20';
export const ERC20_Abi = require('./ERC20.json') as Tagged<AbiItem[], ERC20>;

import type { ERC20Snapshot } from '../typechain/ERC20Snapshot';
export const ERC20Snapshot_Abi = require('./ERC20Snapshot.json') as Tagged<
  AbiItem[],
  ERC20Snapshot
>;

import type { ExpandedERC20 } from '../typechain/ExpandedERC20';
export const ExpandedERC20_Abi = require('./ExpandedERC20.json') as Tagged<
  AbiItem[],
  ExpandedERC20
>;

import type { ExpandedIERC20 } from '../typechain/ExpandedIERC20';
export const ExpandedIERC20_Abi = require('./ExpandedIERC20.json') as Tagged<
  AbiItem[],
  ExpandedIERC20
>;

import type { FeePayerPoolParty } from '../typechain/FeePayerPoolParty';
export const FeePayerPoolParty_Abi = require('./FeePayerPoolParty.json') as Tagged<
  AbiItem[],
  FeePayerPoolParty
>;

import type { FeePayerPoolPartyLib } from '../typechain/FeePayerPoolPartyLib';
export const FeePayerPoolPartyLib_Abi = require('./FeePayerPoolPartyLib.json') as Tagged<
  AbiItem[],
  FeePayerPoolPartyLib
>;

import type { FinancialContractsAdmin } from '../typechain/FinancialContractsAdmin';
export const FinancialContractsAdmin_Abi = require('./FinancialContractsAdmin.json') as Tagged<
  AbiItem[],
  FinancialContractsAdmin
>;

import type { Finder } from '../typechain/Finder';
export const Finder_Abi = require('./Finder.json') as Tagged<AbiItem[], Finder>;

import type { FinderInterface } from '../typechain/FinderInterface';
export const FinderInterface_Abi = require('./FinderInterface.json') as Tagged<
  AbiItem[],
  FinderInterface
>;

import type { Governor } from '../typechain/Governor';
export const Governor_Abi = require('./Governor.json') as Tagged<
  AbiItem[],
  Governor
>;

import type { HitchensUnorderedKeySet } from '../typechain/HitchensUnorderedKeySet';
export const HitchensUnorderedKeySet_Abi = require('./HitchensUnorderedKeySet.json') as Tagged<
  AbiItem[],
  HitchensUnorderedKeySet
>;

import type { IDeploymentSignature } from '../typechain/IDeploymentSignature';
export const IDeploymentSignature_Abi = require('./IDeploymentSignature.json') as Tagged<
  AbiItem[],
  IDeploymentSignature
>;

import type { IDerivative } from '../typechain/IDerivative';
export const IDerivative_Abi = require('./IDerivative.json') as Tagged<
  AbiItem[],
  IDerivative
>;

import type { IDerivativeDeployment } from '../typechain/IDerivativeDeployment';
export const IDerivativeDeployment_Abi = require('./IDerivativeDeployment.json') as Tagged<
  AbiItem[],
  IDerivativeDeployment
>;

import type { IERC20 } from '../typechain/IERC20';
export const IERC20_Abi = require('./IERC20.json') as Tagged<AbiItem[], IERC20>;

import type { IERC20Standard } from '../typechain/IERC20Standard';
export const IERC20Standard_Abi = require('./IERC20Standard.json') as Tagged<
  AbiItem[],
  IERC20Standard
>;

import type { IRole } from '../typechain/IRole';
export const IRole_Abi = require('./IRole.json') as Tagged<AbiItem[], IRole>;

import type { IStandardERC20 } from '../typechain/IStandardERC20';
export const IStandardERC20_Abi = require('./IStandardERC20.json') as Tagged<
  AbiItem[],
  IStandardERC20
>;

import type { ISynthereumChainlinkPriceFeed } from '../typechain/ISynthereumChainlinkPriceFeed';
export const ISynthereumChainlinkPriceFeed_Abi = require('./ISynthereumChainlinkPriceFeed.json') as Tagged<
  AbiItem[],
  ISynthereumChainlinkPriceFeed
>;

import type { ISynthereumDeployer } from '../typechain/ISynthereumDeployer';
export const ISynthereumDeployer_Abi = require('./ISynthereumDeployer.json') as Tagged<
  AbiItem[],
  ISynthereumDeployer
>;

import type { ISynthereumFactoryVersioning } from '../typechain/ISynthereumFactoryVersioning';
export const ISynthereumFactoryVersioning_Abi = require('./ISynthereumFactoryVersioning.json') as Tagged<
  AbiItem[],
  ISynthereumFactoryVersioning
>;

import type { ISynthereumFinder } from '../typechain/ISynthereumFinder';
export const ISynthereumFinder_Abi = require('./ISynthereumFinder.json') as Tagged<
  AbiItem[],
  ISynthereumFinder
>;

import type { ISynthereumPool } from '../typechain/ISynthereumPool';
export const ISynthereumPool_Abi = require('./ISynthereumPool.json') as Tagged<
  AbiItem[],
  ISynthereumPool
>;

import type { ISynthereumPoolDeployment } from '../typechain/ISynthereumPoolDeployment';
export const ISynthereumPoolDeployment_Abi = require('./ISynthereumPoolDeployment.json') as Tagged<
  AbiItem[],
  ISynthereumPoolDeployment
>;

import type { ISynthereumPoolGeneral } from '../typechain/ISynthereumPoolGeneral';
export const ISynthereumPoolGeneral_Abi = require('./ISynthereumPoolGeneral.json') as Tagged<
  AbiItem[],
  ISynthereumPoolGeneral
>;

import type { ISynthereumPoolInteraction } from '../typechain/ISynthereumPoolInteraction';
export const ISynthereumPoolInteraction_Abi = require('./ISynthereumPoolInteraction.json') as Tagged<
  AbiItem[],
  ISynthereumPoolInteraction
>;

import type { ISynthereumPoolOnChainPriceFeed } from '../typechain/ISynthereumPoolOnChainPriceFeed';
export const ISynthereumPoolOnChainPriceFeed_Abi = require('./ISynthereumPoolOnChainPriceFeed.json') as Tagged<
  AbiItem[],
  ISynthereumPoolOnChainPriceFeed
>;

import type { ISynthereumPoolRegistry } from '../typechain/ISynthereumPoolRegistry';
export const ISynthereumPoolRegistry_Abi = require('./ISynthereumPoolRegistry.json') as Tagged<
  AbiItem[],
  ISynthereumPoolRegistry
>;

import type { ISynthereumPriceFeed } from '../typechain/ISynthereumPriceFeed';
export const ISynthereumPriceFeed_Abi = require('./ISynthereumPriceFeed.json') as Tagged<
  AbiItem[],
  ISynthereumPriceFeed
>;

import type { IdentifierWhitelist } from '../typechain/IdentifierWhitelist';
export const IdentifierWhitelist_Abi = require('./IdentifierWhitelist.json') as Tagged<
  AbiItem[],
  IdentifierWhitelist
>;

import type { IdentifierWhitelistInterface } from '../typechain/IdentifierWhitelistInterface';
export const IdentifierWhitelistInterface_Abi = require('./IdentifierWhitelistInterface.json') as Tagged<
  AbiItem[],
  IdentifierWhitelistInterface
>;

import type { MintableBurnableERC20 } from '../typechain/MintableBurnableERC20';
export const MintableBurnableERC20_Abi = require('./MintableBurnableERC20.json') as Tagged<
  AbiItem[],
  MintableBurnableERC20
>;

import type { MintableBurnableIERC20 } from '../typechain/MintableBurnableIERC20';
export const MintableBurnableIERC20_Abi = require('./MintableBurnableIERC20.json') as Tagged<
  AbiItem[],
  MintableBurnableIERC20
>;

import type { MintableBurnableSyntheticToken } from '../typechain/MintableBurnableSyntheticToken';
export const MintableBurnableSyntheticToken_Abi = require('./MintableBurnableSyntheticToken.json') as Tagged<
  AbiItem[],
  MintableBurnableSyntheticToken
>;

import type { MintableBurnableTokenFactory } from '../typechain/MintableBurnableTokenFactory';
export const MintableBurnableTokenFactory_Abi = require('./MintableBurnableTokenFactory.json') as Tagged<
  AbiItem[],
  MintableBurnableTokenFactory
>;

import type { MockOracle } from '../typechain/MockOracle';
export const MockOracle_Abi = require('./MockOracle.json') as Tagged<
  AbiItem[],
  MockOracle
>;

import type { MultiRole } from '../typechain/MultiRole';
export const MultiRole_Abi = require('./MultiRole.json') as Tagged<
  AbiItem[],
  MultiRole
>;

import type { OptimisticOracle } from '../typechain/OptimisticOracle';
export const OptimisticOracle_Abi = require('./OptimisticOracle.json') as Tagged<
  AbiItem[],
  OptimisticOracle
>;

import type { OptimisticOracleInterface } from '../typechain/OptimisticOracleInterface';
export const OptimisticOracleInterface_Abi = require('./OptimisticOracleInterface.json') as Tagged<
  AbiItem[],
  OptimisticOracleInterface
>;

import type { OptimisticRequester } from '../typechain/OptimisticRequester';
export const OptimisticRequester_Abi = require('./OptimisticRequester.json') as Tagged<
  AbiItem[],
  OptimisticRequester
>;

import type { OracleAncillaryInterface } from '../typechain/OracleAncillaryInterface';
export const OracleAncillaryInterface_Abi = require('./OracleAncillaryInterface.json') as Tagged<
  AbiItem[],
  OracleAncillaryInterface
>;

import type { OracleInterface } from '../typechain/OracleInterface';
export const OracleInterface_Abi = require('./OracleInterface.json') as Tagged<
  AbiItem[],
  OracleInterface
>;

import type { OracleInterfaces } from '../typechain/OracleInterfaces';
export const OracleInterfaces_Abi = require('./OracleInterfaces.json') as Tagged<
  AbiItem[],
  OracleInterfaces
>;

import type { Ownable } from '../typechain/Ownable';
export const Ownable_Abi = require('./Ownable.json') as Tagged<
  AbiItem[],
  Ownable
>;

import type { PerpetualLiquidatablePoolParty } from '../typechain/PerpetualLiquidatablePoolParty';
export const PerpetualLiquidatablePoolParty_Abi = require('./PerpetualLiquidatablePoolParty.json') as Tagged<
  AbiItem[],
  PerpetualLiquidatablePoolParty
>;

import type { PerpetualLiquidatablePoolPartyLib } from '../typechain/PerpetualLiquidatablePoolPartyLib';
export const PerpetualLiquidatablePoolPartyLib_Abi = require('./PerpetualLiquidatablePoolPartyLib.json') as Tagged<
  AbiItem[],
  PerpetualLiquidatablePoolPartyLib
>;

import type { PerpetualPoolParty } from '../typechain/PerpetualPoolParty';
export const PerpetualPoolParty_Abi = require('./PerpetualPoolParty.json') as Tagged<
  AbiItem[],
  PerpetualPoolParty
>;

import type { PerpetualPoolPartyCreator } from '../typechain/PerpetualPoolPartyCreator';
export const PerpetualPoolPartyCreator_Abi = require('./PerpetualPoolPartyCreator.json') as Tagged<
  AbiItem[],
  PerpetualPoolPartyCreator
>;

import type { PerpetualPositionManagerPoolParty } from '../typechain/PerpetualPositionManagerPoolParty';
export const PerpetualPositionManagerPoolParty_Abi = require('./PerpetualPositionManagerPoolParty.json') as Tagged<
  AbiItem[],
  PerpetualPositionManagerPoolParty
>;

import type { PerpetualPositionManagerPoolPartyLib } from '../typechain/PerpetualPositionManagerPoolPartyLib';
export const PerpetualPositionManagerPoolPartyLib_Abi = require('./PerpetualPositionManagerPoolPartyLib.json') as Tagged<
  AbiItem[],
  PerpetualPositionManagerPoolPartyLib
>;

import type { Registry } from '../typechain/Registry';
export const Registry_Abi = require('./Registry.json') as Tagged<
  AbiItem[],
  Registry
>;

import type { RegistryInterface } from '../typechain/RegistryInterface';
export const RegistryInterface_Abi = require('./RegistryInterface.json') as Tagged<
  AbiItem[],
  RegistryInterface
>;

import type { Store } from '../typechain/Store';
export const Store_Abi = require('./Store.json') as Tagged<AbiItem[], Store>;

import type { StoreInterface } from '../typechain/StoreInterface';
export const StoreInterface_Abi = require('./StoreInterface.json') as Tagged<
  AbiItem[],
  StoreInterface
>;

import type { SynthereumChainlinkPriceFeed } from '../typechain/SynthereumChainlinkPriceFeed';
export const SynthereumChainlinkPriceFeed_Abi = require('./SynthereumChainlinkPriceFeed.json') as Tagged<
  AbiItem[],
  SynthereumChainlinkPriceFeed
>;

import type { SynthereumDeployer } from '../typechain/SynthereumDeployer';
export const SynthereumDeployer_Abi = require('./SynthereumDeployer.json') as Tagged<
  AbiItem[],
  SynthereumDeployer
>;

import type { SynthereumDerivativeFactory } from '../typechain/SynthereumDerivativeFactory';
export const SynthereumDerivativeFactory_Abi = require('./SynthereumDerivativeFactory.json') as Tagged<
  AbiItem[],
  SynthereumDerivativeFactory
>;

import type { SynthereumFactoryVersioning } from '../typechain/SynthereumFactoryVersioning';
export const SynthereumFactoryVersioning_Abi = require('./SynthereumFactoryVersioning.json') as Tagged<
  AbiItem[],
  SynthereumFactoryVersioning
>;

import type { SynthereumFinder } from '../typechain/SynthereumFinder';
export const SynthereumFinder_Abi = require('./SynthereumFinder.json') as Tagged<
  AbiItem[],
  SynthereumFinder
>;

import type { SynthereumInterfaces } from '../typechain/SynthereumInterfaces';
export const SynthereumInterfaces_Abi = require('./SynthereumInterfaces.json') as Tagged<
  AbiItem[],
  SynthereumInterfaces
>;

import type { SynthereumPool } from '../typechain/SynthereumPool';
export const SynthereumPool_Abi = require('./SynthereumPool.json') as Tagged<
  AbiItem[],
  SynthereumPool
>;

import type { SynthereumPoolCreator } from '../typechain/SynthereumPoolCreator';
export const SynthereumPoolCreator_Abi = require('./SynthereumPoolCreator.json') as Tagged<
  AbiItem[],
  SynthereumPoolCreator
>;

import type { SynthereumPoolFactory } from '../typechain/SynthereumPoolFactory';
export const SynthereumPoolFactory_Abi = require('./SynthereumPoolFactory.json') as Tagged<
  AbiItem[],
  SynthereumPoolFactory
>;

import type { SynthereumPoolLib } from '../typechain/SynthereumPoolLib';
export const SynthereumPoolLib_Abi = require('./SynthereumPoolLib.json') as Tagged<
  AbiItem[],
  SynthereumPoolLib
>;

import type { SynthereumPoolOnChainPriceFeed } from '../typechain/SynthereumPoolOnChainPriceFeed';
export const SynthereumPoolOnChainPriceFeed_Abi = require('./SynthereumPoolOnChainPriceFeed.json') as Tagged<
  AbiItem[],
  SynthereumPoolOnChainPriceFeed
>;

import type { SynthereumPoolOnChainPriceFeedCreator } from '../typechain/SynthereumPoolOnChainPriceFeedCreator';
export const SynthereumPoolOnChainPriceFeedCreator_Abi = require('./SynthereumPoolOnChainPriceFeedCreator.json') as Tagged<
  AbiItem[],
  SynthereumPoolOnChainPriceFeedCreator
>;

import type { SynthereumPoolOnChainPriceFeedFactory } from '../typechain/SynthereumPoolOnChainPriceFeedFactory';
export const SynthereumPoolOnChainPriceFeedFactory_Abi = require('./SynthereumPoolOnChainPriceFeedFactory.json') as Tagged<
  AbiItem[],
  SynthereumPoolOnChainPriceFeedFactory
>;

import type { SynthereumPoolOnChainPriceFeedLib } from '../typechain/SynthereumPoolOnChainPriceFeedLib';
export const SynthereumPoolOnChainPriceFeedLib_Abi = require('./SynthereumPoolOnChainPriceFeedLib.json') as Tagged<
  AbiItem[],
  SynthereumPoolOnChainPriceFeedLib
>;

import type { SynthereumPoolRegistry } from '../typechain/SynthereumPoolRegistry';
export const SynthereumPoolRegistry_Abi = require('./SynthereumPoolRegistry.json') as Tagged<
  AbiItem[],
  SynthereumPoolRegistry
>;

import type { SynthereumSyntheticTokenFactory } from '../typechain/SynthereumSyntheticTokenFactory';
export const SynthereumSyntheticTokenFactory_Abi = require('./SynthereumSyntheticTokenFactory.json') as Tagged<
  AbiItem[],
  SynthereumSyntheticTokenFactory
>;

import type { SynthereumTIC } from '../typechain/SynthereumTIC';
export const SynthereumTIC_Abi = require('./SynthereumTIC.json') as Tagged<
  AbiItem[],
  SynthereumTIC
>;

import type { SynthereumTICFactory } from '../typechain/SynthereumTICFactory';
export const SynthereumTICFactory_Abi = require('./SynthereumTICFactory.json') as Tagged<
  AbiItem[],
  SynthereumTICFactory
>;

import type { SynthereumTICInterface } from '../typechain/SynthereumTICInterface';
export const SynthereumTICInterface_Abi = require('./SynthereumTICInterface.json') as Tagged<
  AbiItem[],
  SynthereumTICInterface
>;

import type { TICCreator } from '../typechain/TICCreator';
export const TICCreator_Abi = require('./TICCreator.json') as Tagged<
  AbiItem[],
  TICCreator
>;

import type { Testable } from '../typechain/Testable';
export const Testable_Abi = require('./Testable.json') as Tagged<
  AbiItem[],
  Testable
>;

import type { TestnetERC20 } from '../typechain/TestnetERC20';
export const TestnetERC20_Abi = require('./TestnetERC20.json') as Tagged<
  AbiItem[],
  TestnetERC20
>;

import type { Timer } from '../typechain/Timer';
export const Timer_Abi = require('./Timer.json') as Tagged<AbiItem[], Timer>;

import type { TokenMigrator } from '../typechain/TokenMigrator';
export const TokenMigrator_Abi = require('./TokenMigrator.json') as Tagged<
  AbiItem[],
  TokenMigrator
>;

import type { Voting } from '../typechain/Voting';
export const Voting_Abi = require('./Voting.json') as Tagged<AbiItem[], Voting>;

import type { VotingAncillaryInterface } from '../typechain/VotingAncillaryInterface';
export const VotingAncillaryInterface_Abi = require('./VotingAncillaryInterface.json') as Tagged<
  AbiItem[],
  VotingAncillaryInterface
>;

import type { VotingInterface } from '../typechain/VotingInterface';
export const VotingInterface_Abi = require('./VotingInterface.json') as Tagged<
  AbiItem[],
  VotingInterface
>;

import type { VotingToken } from '../typechain/VotingToken';
export const VotingToken_Abi = require('./VotingToken.json') as Tagged<
  AbiItem[],
  VotingToken
>;

import type { Withdrawable } from '../typechain/Withdrawable';
export const Withdrawable_Abi = require('./Withdrawable.json') as Tagged<
  AbiItem[],
  Withdrawable
>;
